baseURL: "https://almendrofloracion.netlify.app/"
title: Howard van Meer & Daniel Pacheco
theme: hugo-theme-m10c
paginate: 8
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 2
    - identifier: about
      name: About
      url: /about/
      weight: 3
params:
  author: John Doe
  description: Floraci√≥n almendro.
  menu_item_separator: ' - '
  social:
    - icon: github
      name: Github
      url: https://github.com/gohugoio
    - icon: twitter
      name: Twitter
      url: https://twitter.com/gohugoio
